POPULAR_CLUBS = [
    {"id": "141", "name": "Galatasaray", "slug": "galatasaray-istanbul", "country": "Türkiye", "league": "Süper Lig"},
    {"id": "36", "name": "Fenerbahçe", "slug": "fenerbahce-istanbul", "country": "Türkiye", "league": "Süper Lig"},
    {"id": "114", "name": "Beşiktaş JK", "slug": "besiktas-istanbul", "country": "Türkiye", "league": "Süper Lig"},
    {"id": "449", "name": "Trabzonspor", "slug": "trabzonspor", "country": "Türkiye", "league": "Süper Lig"},
    {"id": "418", "name": "Real Madrid", "slug": "real-madrid", "country": "Spain", "league": "LaLiga"},
    {"id": "131", "name": "FC Barcelona", "slug": "fc-barcelona", "country": "Spain", "league": "LaLiga"},
    {"id": "11", "name": "Arsenal FC", "slug": "fc-arsenal", "country": "England", "league": "Premier League"},
    {"id": "631", "name": "Chelsea FC", "slug": "chelsea-fc", "country": "England", "league": "Premier League"},
    {"id": "31", "name": "Liverpool FC", "slug": "fc-liverpool", "country": "England", "league": "Premier League"},
    {"id": "985", "name": "Manchester United", "slug": "manchester-united", "country": "England", "league": "Premier League"},
    {"id": "281", "name": "Manchester City", "slug": "manchester-city", "country": "England", "league": "Premier League"},
    {"id": "27", "name": "Bayern Munich", "slug": "fc-bayern-munchen", "country": "Germany", "league": "Bundesliga"},
    {"id": "16", "name": "Borussia Dortmund", "slug": "borussia-dortmund", "country": "Germany", "league": "Bundesliga"},
    {"id": "583", "name": "Paris Saint-Germain", "slug": "paris-saint-germain", "country": "France", "league": "Ligue 1"},
    {"id": "506", "name": "Juventus FC", "slug": "juventus-turin", "country": "Italy", "league": "Serie A"},
    {"id": "46", "name": "Inter Milan", "slug": "inter-mailand", "country": "Italy", "league": "Serie A"},
    {"id": "5", "name": "AC Milan", "slug": "ac-mailand", "country": "Italy", "league": "Serie A"},
    {"id": "244", "name": "AS Roma", "slug": "as-rom", "country": "Italy", "league": "Serie A"},
    {"id": "13", "name": "Atlético de Madrid", "slug": "atletico-madrid", "country": "Spain", "league": "LaLiga"},
]
